#!/usr/bin/env bash
# Discover, pair, trust, and persist BAFX / ELM327 classic Bluetooth adapter.
# Android-only ELM clones are BR/EDR (classic), not BLE — scan accordingly.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "${SCRIPT_DIR}/lib.sh"

load_config
require_root

mkdir -p "${OBD_BRIDGE_ETC}"

save_device() {
  local mac="$1"
  local name="${2:-unknown}"
  cat >"${DEVICE_ENV}" <<EOF
# Generated by pair-bafx.sh — do not edit unless you know the MAC.
BT_MAC=${mac}
BT_NAME=${name}
EOF
  chmod 644 "${DEVICE_ENV}"
  log "Saved ${mac} (${name}) to ${DEVICE_ENV}"
}

normalize_mac() {
  echo "$1" | tr '[:lower:]' '[:upper:]'
}

ensure_agent() {
  bluetoothctl power on >/dev/null 2>&1 || true
  bluetoothctl pairable on >/dev/null 2>&1 || true
  bluetoothctl discoverable off >/dev/null 2>&1 || true
  printf 'agent NoInputNoOutput\ndefault-agent\n' | bluetoothctl >/dev/null 2>&1 || true
}

# Classic BR/EDR inquiry — required for older Android-only OBDII dongles.
start_classic_scan() {
  bluetoothctl power on >/dev/null 2>&1 || true
  bluetoothctl pairable on >/dev/null 2>&1 || true
  bluetoothctl scan off >/dev/null 2>&1 || true
  # Prefer classic inquiry (bredr). Fall back to auto if filter unsupported.
  if printf 'menu scan\nclear\ntransport bredr\nback\nscan on\n' | bluetoothctl >/dev/null 2>&1; then
    append_event "classic scan (bredr) on"
    return 0
  fi
  if bluetoothctl scan bredr >/dev/null 2>&1; then
    append_event "classic scan bredr on"
    return 0
  fi
  bluetoothctl scan on >/dev/null 2>&1 || true
  append_event "scan on (auto — bredr filter failed)"
}

stop_scan() {
  bluetoothctl scan off >/dev/null 2>&1 || true
}

# hcitool classic inquiry (very reliable for ELM clones when available)
hcitool_classic_scan() {
  local secs="${1:-12}"
  local out=""
  if ! command -v hcitool >/dev/null 2>&1; then
    return 0
  fi
  # length is in 1.28s units; 10 ≈ 12.8s
  local length=$(( (secs + 1) * 10 / 13 ))
  [[ "${length}" -lt 4 ]] && length=4
  [[ "${length}" -gt 16 ]] && length=16
  append_event "hcitool classic inquiry ${secs}s"
  set +e
  out="$(timeout $((secs + 5)) hcitool -i hci0 scan --flush --length="${length}" 2>/dev/null || true)"
  set -e
  if [[ -n "${out}" ]]; then
    local dir="${OBD_BRIDGE_STATE:-/var/lib/obd-bridge}"
    mkdir -p "${dir}"
    printf '%s\n' "${out}" >"${dir}/hcitool-last.txt"
    printf '%s\n' "${out}" >>"${dir}/bt-scan.log"
  fi
  # Emit Device-like lines for matching: "AA:BB:…  Name"
  printf '%s\n' "${out}" | awk '
    /^[[:space:]]*[0-9A-Fa-f:]{17}[[:space:]]+/ {
      mac=$1; $1=""; sub(/^[[:space:]]+/,"");
      print "Device " toupper(mac) " " $0
    }'
}

pair_mac() {
  local mac="$1"
  local name="${2:-}"
  local agent_pid=""
  mac="$(normalize_mac "${mac}")"

  log "Pairing ${mac} with PIN ${BT_PIN}…"
  ensure_agent

  if command -v bt-agent >/dev/null 2>&1; then
    pkill -f 'bt-agent' >/dev/null 2>&1 || true
    bt-agent -c NoInputNoOutput >/dev/null 2>&1 &
    agent_pid=$!
    sleep 1
  fi

  bluetoothctl remove "${mac}" >/dev/null 2>&1 || true
  start_classic_scan
  sleep 3

  if command -v expect >/dev/null 2>&1; then
    expect <<EOF
set timeout 45
spawn bluetoothctl
expect -re {# |\\[.*\\]# }
send "pair ${mac}\r"
expect {
  "Passkey" { send "${BT_PIN}\r"; exp_continue }
  "PIN" { send "${BT_PIN}\r"; exp_continue }
  "Confirm passkey" { send "yes\r"; exp_continue }
  "Authorize service" { send "yes\r"; exp_continue }
  "Pairing successful" {}
  "Failed to pair" { exit 1 }
  timeout { exit 1 }
}
send "trust ${mac}\r"
expect -re {# |\\[.*\\]# }
send "connect ${mac}\r"
expect -re {# |\\[.*\\]# }
send "quit\r"
expect eof
EOF
  else
    bluetoothctl pair "${mac}" || true
    sleep 2
    bluetoothctl trust "${mac}"
    bluetoothctl connect "${mac}" || true
  fi

  if [[ -n "${agent_pid}" ]]; then
    kill "${agent_pid}" >/dev/null 2>&1 || true
  fi

  stop_scan
  bluetoothctl trust "${mac}" >/dev/null 2>&1 || true

  if bluetoothctl info "${mac}" 2>/dev/null | grep -qi 'Trusted: yes'; then
    save_device "${mac}" "${name}"
    return 0
  fi
  if bluetoothctl info "${mac}" 2>/dev/null | grep -qi 'Paired: yes'; then
    bluetoothctl trust "${mac}" >/dev/null 2>&1 || true
    save_device "${mac}" "${name}"
    return 0
  fi

  err "Failed to pair/trust ${mac}"
  return 1
}

discover_mac() {
  local scan_secs="${BT_SCAN_SECONDS:-30}"
  log "Classic BT scan ${scan_secs}s for /${BT_NAME_REGEX}/ (Android ELM = BR/EDR)…"
  append_event "classic scan ${scan_secs}s for OBDII"

  # Hostapd on the same Pi 3 radio kills classic inquiry — stop if running.
  if systemctl is-active --quiet hostapd 2>/dev/null; then
    append_event "stopping hostapd for classic BT scan"
    systemctl stop hostapd 2>/dev/null || true
    sleep 1
  fi

  start_classic_scan

  local elapsed=0
  local step=5
  local hci_chunk=""
  while [[ "${elapsed}" -lt "${scan_secs}" ]]; do
    sleep "${step}"
    elapsed=$((elapsed + step))

    if bluetoothctl devices 2>/dev/null | grep -Eiq "${BT_NAME_REGEX}"; then
      stop_scan
      dump_bt_scan "autopair-classic-match"
      local line mac name
      while IFS= read -r line; do
        mac="$(echo "${line}" | awk '{print $2}')"
        name="$(echo "${line}" | cut -d' ' -f3-)"
        if echo "${name}" | grep -Eiq "${BT_NAME_REGEX}"; then
          append_event "FOUND ${name} ${mac}"
          printf '%s\t%s\n' "$(normalize_mac "${mac}")" "${name}"
          return 0
        fi
      done < <(bluetoothctl devices 2>/dev/null || true)
    fi

    # Mid-scan classic inquiry via hcitool (every 10s)
    if [[ $((elapsed % 10)) -eq 0 ]] || [[ "${elapsed}" -ge "${scan_secs}" ]]; then
      hci_chunk="$(hcitool_classic_scan 8 || true)"
      if printf '%s\n' "${hci_chunk}" | grep -Eiq "${BT_NAME_REGEX}"; then
        stop_scan
        dump_bt_scan "autopair-hcitool-match"
        local line mac name
        while IFS= read -r line; do
          mac="$(echo "${line}" | awk '{print $2}')"
          name="$(echo "${line}" | cut -d' ' -f3-)"
          if echo "${name}" | grep -Eiq "${BT_NAME_REGEX}"; then
            append_event "FOUND ${name} ${mac} (hcitool)"
            printf '%s\t%s\n' "$(normalize_mac "${mac}")" "${name}"
            return 0
          fi
        done < <(printf '%s\n' "${hci_chunk}")
      fi
    fi

    if [[ $((elapsed % 10)) -eq 0 ]]; then
      append_event "still scanning classic… ${elapsed}s"
    fi
  done

  # Final hcitool pass
  hci_chunk="$(hcitool_classic_scan 12 || true)"
  stop_scan
  dump_bt_scan "autopair-classic-scan"

  if printf '%s\n' "${hci_chunk}" | grep -Eiq "${BT_NAME_REGEX}"; then
    local line mac name
    while IFS= read -r line; do
      mac="$(echo "${line}" | awk '{print $2}')"
      name="$(echo "${line}" | cut -d' ' -f3-)"
      if echo "${name}" | grep -Eiq "${BT_NAME_REGEX}"; then
        append_event "FOUND ${name} ${mac} (hcitool)"
        printf '%s\t%s\n' "$(normalize_mac "${mac}")" "${name}"
        return 0
      fi
    done < <(printf '%s\n' "${hci_chunk}")
  fi

  local line mac name
  while IFS= read -r line; do
    mac="$(echo "${line}" | awk '{print $2}')"
    name="$(echo "${line}" | cut -d' ' -f3-)"
    if echo "${name}" | grep -Eiq "${BT_NAME_REGEX}"; then
      append_event "FOUND ${name} ${mac}"
      printf '%s\t%s\n' "$(normalize_mac "${mac}")" "${name}"
      return 0
    fi
  done < <(bluetoothctl devices 2>/dev/null || true)

  local count
  count="$(bluetoothctl devices 2>/dev/null | wc -l | tr -d ' ')"
  append_event "scan done: ${count:-0} devices, no OBDII (classic)"
  while IFS= read -r line; do
    name="$(echo "${line}" | cut -d' ' -f3-)"
    mac="$(echo "${line}" | awk '{print $2}')"
    if [[ -z "${name}" || "${name}" == "${mac}" ]]; then
      continue
    fi
    append_event "saw: $(echo "${name}" | cut -c1-28)"
  done < <(bluetoothctl devices 2>/dev/null | head -n 8 || true)

  err "No classic Bluetooth device matched /${BT_NAME_REGEX}/"
  err "Named BT: $(bluetoothctl devices 2>/dev/null | cut -d' ' -f3- | grep -v '^$' | head -n 4 | tr '\n' ',' | sed 's/,$//' || echo none)"
  err "Nearby count: ${count:-0}. Need classic OBDII; keep ENABLE_AP=0 on Pi 3"
  return 1
}

main() {
  if ! bt_adapter_ready; then
    err "Bluetooth adapter not ready. Is bluez installed and btusb loaded?"
    exit 1
  fi

  local mac name=""
  if [[ -n "${BT_MAC:-}" ]]; then
    mac="$(normalize_mac "${BT_MAC}")"
    name="$(bluetoothctl info "${mac}" 2>/dev/null | awk -F': ' '/Name:/{print $2; exit}' || echo "configured")"
    log "Using configured BT_MAC=${mac}"
  else
    local discovered
    discovered="$(discover_mac)"
    mac="$(echo "${discovered}" | awk -F'\t' '{print $1}')"
    name="$(echo "${discovered}" | awk -F'\t' '{print $2}')"
    log "Discovered ${mac} (${name})"
  fi

  pair_mac "${mac}" "${name}"
  log "Pairing complete."
}

main "$@"
