#!/usr/bin/env bash
# Discover, pair, trust, and persist BAFX / ELM327 Bluetooth adapter MAC.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "${SCRIPT_DIR}/lib.sh"

load_config
require_root

mkdir -p "${OBD_BRIDGE_ETC}"

save_device() {
  local mac="$1"
  local name="${2:-unknown}"
  cat >"${DEVICE_ENV}" <<EOF
# Generated by pair-bafx.sh — do not edit unless you know the MAC.
BT_MAC=${mac}
BT_NAME=${name}
EOF
  chmod 644 "${DEVICE_ENV}"
  log "Saved ${mac} (${name}) to ${DEVICE_ENV}"
}

normalize_mac() {
  echo "$1" | tr '[:lower:]' '[:upper:]'
}

ensure_agent() {
  # Non-interactive pairing agent with fixed PIN for classic ELM clones.
  if ! pgrep -f 'bluetoothctl.*agent' >/dev/null 2>&1; then
    true
  fi
  bluetoothctl power on >/dev/null 2>&1 || true
  bluetoothctl pairable on >/dev/null 2>&1 || true
  bluetoothctl discoverable off >/dev/null 2>&1 || true
  printf 'agent NoInputNoOutput\ndefault-agent\n' | bluetoothctl >/dev/null 2>&1 || true
}

pair_mac() {
  local mac="$1"
  local name="${2:-}"
  local agent_pid=""
  mac="$(normalize_mac "${mac}")"

  log "Pairing ${mac} with PIN ${BT_PIN}…"
  ensure_agent

  # Prefer bluez-tools if available for PIN; fall back to bluetoothctl expect-style.
  if command -v bt-agent >/dev/null 2>&1; then
    pkill -f 'bt-agent' >/dev/null 2>&1 || true
    bt-agent -c NoInputNoOutput >/dev/null 2>&1 &
    agent_pid=$!
    sleep 1
  fi

  bluetoothctl remove "${mac}" >/dev/null 2>&1 || true
  bluetoothctl scan on >/dev/null 2>&1 || true
  sleep 2

  # Many ELM327 adapters use PIN 1234; register via bluetoothctl expect if present.
  if command -v expect >/dev/null 2>&1; then
    expect <<EOF
set timeout 45
spawn bluetoothctl
expect "# "
send "pair ${mac}\r"
expect {
  "Passkey" { send "${BT_PIN}\r"; exp_continue }
  "PIN" { send "${BT_PIN}\r"; exp_continue }
  "Confirm passkey" { send "yes\r"; exp_continue }
  "Authorize service" { send "yes\r"; exp_continue }
  "Pairing successful" {}
  "Failed to pair" { exit 1 }
  timeout { exit 1 }
}
send "trust ${mac}\r"
expect "# "
send "connect ${mac}\r"
expect "# "
send "quit\r"
expect eof
EOF
  else
    bluetoothctl pair "${mac}" || true
    sleep 2
    bluetoothctl trust "${mac}"
    bluetoothctl connect "${mac}" || true
  fi

  if [[ -n "${agent_pid}" ]]; then
    kill "${agent_pid}" >/dev/null 2>&1 || true
  fi

  bluetoothctl scan off >/dev/null 2>&1 || true
  bluetoothctl trust "${mac}" >/dev/null 2>&1 || true

  if bluetoothctl info "${mac}" 2>/dev/null | grep -qi 'Trusted: yes'; then
    save_device "${mac}" "${name}"
    return 0
  fi

  # Some adapters report paired without Trusted flag momentarily.
  if bluetoothctl info "${mac}" 2>/dev/null | grep -qi 'Paired: yes'; then
    bluetoothctl trust "${mac}" >/dev/null 2>&1 || true
    save_device "${mac}" "${name}"
    return 0
  fi

  err "Failed to pair/trust ${mac}"
  return 1
}

discover_mac() {
  log "Scanning ${BT_SCAN_SECONDS}s for adapters matching /${BT_NAME_REGEX}/ …"
  bluetoothctl power on >/dev/null 2>&1 || true
  bluetoothctl pairable on >/dev/null 2>&1 || true
  bluetoothctl scan on >/dev/null 2>&1 || true
  sleep "${BT_SCAN_SECONDS}"
  bluetoothctl scan off >/dev/null 2>&1 || true

  local line mac name
  # bluetoothctl devices may show previously seen devices too
  while IFS= read -r line; do
    # Device AA:BB:CC:DD:EE:FF Name Here
    mac="$(echo "${line}" | awk '{print $2}')"
    name="$(echo "${line}" | cut -d' ' -f3-)"
    if echo "${name}" | grep -Eiq "${BT_NAME_REGEX}"; then
      printf '%s\t%s\n' "$(normalize_mac "${mac}")" "${name}"
      return 0
    fi
  done < <(bluetoothctl devices 2>/dev/null || true)

  err "No Bluetooth device matched /${BT_NAME_REGEX}/"
  local seen named
  named="$(bluetoothctl devices 2>/dev/null | grep -Eiv 'Device ([0-9A-F:]{17}) \1$' | head -n 6 || true)"
  seen="$(bluetoothctl devices 2>/dev/null | head -n 6 | sed 's/^Device //' || true)"
  if [[ -n "${named}" ]]; then
    err "Named BT: $(echo "${named}" | sed 's/^Device //' | tr '\n' ' ' | cut -c1-120)"
  fi
  if [[ -n "${seen}" ]]; then
    err "Nearby BT: $(echo "${seen}" | tr '\n' ' ' | cut -c1-120)"
  else
    err "Nearby BT: (none discovered — BAFX off, out of range, or already paired to phone)"
  fi
  err "Power the BAFX (ignition ON). If its name is odd, set BT_MAC=.. in ${CONFIG_ENV}"
  return 1
}

main() {
  if ! bt_adapter_ready; then
    err "Bluetooth adapter not ready. Is bluez installed and btusb loaded?"
    exit 1
  fi

  local mac name=""
  if [[ -n "${BT_MAC:-}" ]]; then
    mac="$(normalize_mac "${BT_MAC}")"
    name="$(bluetoothctl info "${mac}" 2>/dev/null | awk -F': ' '/Name:/{print $2; exit}' || echo "configured")"
    log "Using configured BT_MAC=${mac}"
  else
    local discovered
    discovered="$(discover_mac)"
    mac="$(echo "${discovered}" | awk -F'\t' '{print $1}')"
    name="$(echo "${discovered}" | awk -F'\t' '{print $2}')"
    log "Discovered ${mac} (${name})"
  fi

  pair_mac "${mac}" "${name}"
  log "Pairing complete."
}

main "$@"
