#!/usr/bin/env bash
# Discover, pair, trust, and persist BAFX / ELM327 Bluetooth adapter MAC.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "${SCRIPT_DIR}/lib.sh"

load_config
require_root

mkdir -p "${OBD_BRIDGE_ETC}"

save_device() {
  local mac="$1"
  local name="${2:-unknown}"
  cat >"${DEVICE_ENV}" <<EOF
# Generated by pair-bafx.sh — do not edit unless you know the MAC.
BT_MAC=${mac}
BT_NAME=${name}
EOF
  chmod 644 "${DEVICE_ENV}"
  log "Saved ${mac} (${name}) to ${DEVICE_ENV}"
}

normalize_mac() {
  echo "$1" | tr '[:lower:]' '[:upper:]'
}

ensure_agent() {
  # Non-interactive pairing agent with fixed PIN for classic ELM clones.
  if ! pgrep -f 'bluetoothctl.*agent' >/dev/null 2>&1; then
    true
  fi
  bluetoothctl power on >/dev/null 2>&1 || true
  bluetoothctl pairable on >/dev/null 2>&1 || true
  bluetoothctl discoverable off >/dev/null 2>&1 || true
  printf 'agent NoInputNoOutput\ndefault-agent\n' | bluetoothctl >/dev/null 2>&1 || true
}

pair_mac() {
  local mac="$1"
  local name="${2:-}"
  local agent_pid=""
  mac="$(normalize_mac "${mac}")"

  log "Pairing ${mac} with PIN ${BT_PIN}…"
  ensure_agent

  # Prefer bluez-tools if available for PIN; fall back to bluetoothctl expect-style.
  if command -v bt-agent >/dev/null 2>&1; then
    pkill -f 'bt-agent' >/dev/null 2>&1 || true
    bt-agent -c NoInputNoOutput >/dev/null 2>&1 &
    agent_pid=$!
    sleep 1
  fi

  bluetoothctl remove "${mac}" >/dev/null 2>&1 || true
  bluetoothctl scan on >/dev/null 2>&1 || true
  sleep 2

  # Many ELM327 adapters use PIN 1234; register via bluetoothctl expect if present.
  if command -v expect >/dev/null 2>&1; then
    expect <<EOF
set timeout 45
spawn bluetoothctl
expect "# "
send "pair ${mac}\r"
expect {
  "Passkey" { send "${BT_PIN}\r"; exp_continue }
  "PIN" { send "${BT_PIN}\r"; exp_continue }
  "Confirm passkey" { send "yes\r"; exp_continue }
  "Authorize service" { send "yes\r"; exp_continue }
  "Pairing successful" {}
  "Failed to pair" { exit 1 }
  timeout { exit 1 }
}
send "trust ${mac}\r"
expect "# "
send "connect ${mac}\r"
expect "# "
send "quit\r"
expect eof
EOF
  else
    bluetoothctl pair "${mac}" || true
    sleep 2
    bluetoothctl trust "${mac}"
    bluetoothctl connect "${mac}" || true
  fi

  if [[ -n "${agent_pid}" ]]; then
    kill "${agent_pid}" >/dev/null 2>&1 || true
  fi

  bluetoothctl scan off >/dev/null 2>&1 || true
  bluetoothctl trust "${mac}" >/dev/null 2>&1 || true

  if bluetoothctl info "${mac}" 2>/dev/null | grep -qi 'Trusted: yes'; then
    save_device "${mac}" "${name}"
    return 0
  fi

  # Some adapters report paired without Trusted flag momentarily.
  if bluetoothctl info "${mac}" 2>/dev/null | grep -qi 'Paired: yes'; then
    bluetoothctl trust "${mac}" >/dev/null 2>&1 || true
    save_device "${mac}" "${name}"
    return 0
  fi

  err "Failed to pair/trust ${mac}"
  return 1
}

discover_mac() {
  log "Scanning ${BT_SCAN_SECONDS}s for adapters matching /${BT_NAME_REGEX}/ …"
  append_event "BT scan ${BT_SCAN_SECONDS}s (watch for OBDII)"
  bluetoothctl power on >/dev/null 2>&1 || true
  bluetoothctl pairable on >/dev/null 2>&1 || true
  bluetoothctl scan on >/dev/null 2>&1 || true

  local elapsed=0
  local step=5
  while [[ "${elapsed}" -lt "${BT_SCAN_SECONDS}" ]]; do
    sleep "${step}"
    elapsed=$((elapsed + step))
    if [[ "${elapsed}" -gt "${BT_SCAN_SECONDS}" ]]; then
      break
    fi
    # Early exit if we already see a matching name
    if bluetoothctl devices 2>/dev/null | grep -Eiq "${BT_NAME_REGEX}"; then
      append_event "match visible mid-scan (${elapsed}s)"
      break
    fi
    if [[ $((elapsed % 10)) -eq 0 ]]; then
      append_event "still scanning… ${elapsed}s"
    fi
  done
  # Finish remaining sleep if we broke early on match — still give a moment
  bluetoothctl scan off >/dev/null 2>&1 || true

  local line mac name
  while IFS= read -r line; do
    mac="$(echo "${line}" | awk '{print $2}')"
    name="$(echo "${line}" | cut -d' ' -f3-)"
    if echo "${name}" | grep -Eiq "${BT_NAME_REGEX}"; then
      append_event "FOUND ${name} ${mac}"
      printf '%s\t%s\n' "$(normalize_mac "${mac}")" "${name}"
      return 0
    fi
  done < <(bluetoothctl devices 2>/dev/null || true)

  # Surface what we did see on the PiTFT (no SSH needed)
  local count named_line short_name
  count="$(bluetoothctl devices 2>/dev/null | wc -l | tr -d ' ')"
  append_event "scan done: ${count:-0} BT device(s), no OBD name match"
  while IFS= read -r line; do
    name="$(echo "${line}" | cut -d' ' -f3-)"
    mac="$(echo "${line}" | awk '{print $2}')"
    # Skip entries whose "name" is just the MAC repeated
    if [[ -z "${name}" || "${name}" == "${mac}" ]]; then
      continue
    fi
    short_name="$(echo "${name}" | cut -c1-28)"
    append_event "saw: ${short_name}"
  done < <(bluetoothctl devices 2>/dev/null | head -n 8 || true)

  err "No Bluetooth device matched /${BT_NAME_REGEX}/"
  named_line="$(bluetoothctl devices 2>/dev/null | awk '{$1="";$2=""; sub(/^  /,""); print}' | grep -v '^$' | grep -Eiv '^[0-9A-Fa-f:]{17}$' | head -n 4 | tr '\n' ',' | sed 's/,$//' || true)"
  if [[ -n "${named_line}" ]]; then
    err "Named BT: ${named_line}"
  else
    err "Named BT: (none — only unnamed MACs or empty scan)"
  fi
  err "Nearby count: ${count:-0}. Need name OBDII with LED on; forget it on phone/Mac first"
  return 1
}

main() {
  if ! bt_adapter_ready; then
    err "Bluetooth adapter not ready. Is bluez installed and btusb loaded?"
    exit 1
  fi

  local mac name=""
  if [[ -n "${BT_MAC:-}" ]]; then
    mac="$(normalize_mac "${BT_MAC}")"
    name="$(bluetoothctl info "${mac}" 2>/dev/null | awk -F': ' '/Name:/{print $2; exit}' || echo "configured")"
    log "Using configured BT_MAC=${mac}"
  else
    local discovered
    discovered="$(discover_mac)"
    mac="$(echo "${discovered}" | awk -F'\t' '{print $1}')"
    name="$(echo "${discovered}" | awk -F'\t' '{print $2}')"
    log "Discovered ${mac} (${name})"
  fi

  pair_mac "${mac}" "${name}"
  log "Pairing complete."
}

main "$@"
